[package]
name = "apibara-sink-webhook"
version = "0.6.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "apibara_sink_webhook"
path = "src/lib.rs"

[[bin]]
name = "apibara-sink-webhook"
path = "src/bin.rs"

[dependencies]
apibara-observability = { path = "../../observability" }
apibara-dna-protocol = { path = "../../dna/protocol" }
apibara-sink-common = { path = "../sink-common" }
async-trait.workspace = true
clap.workspace = true
error-stack.workspace = true
http.workspace = true
prost.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[target.'cfg(not(windows))'.dependencies]
jemallocator.workspace = true

[dev-dependencies]
wiremock.workspace = true
