[package]
name = "apibara-sink-parquet"
version = "0.6.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "apibara_sink_parquet"
path = "src/lib.rs"

[[bin]]
name = "apibara-sink-parquet"
path = "src/bin.rs"

[dependencies]
aws-sdk-s3 = "1.13.0"
aws-config = "1.1.3"
apibara-observability = { path = "../../observability" }
apibara-dna-protocol = { path = "../../dna/protocol" }
apibara-sink-common = { path = "../sink-common" }
arrow = { version = "41.0.0", default-features = false, features = [
    "arrow-json",
    "json",
] }
async-trait.workspace = true
error-stack.workspace = true
clap.workspace = true
parquet = { version = "41.0.0", default-features = false, features = [
    "arrow",
    "arrow-array",
    "arrow-schema",
] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[target.'cfg(not(windows))'.dependencies]
jemallocator.workspace = true

[dev-dependencies]
tempdir.workspace = true
